export const SHORT_NAMES = Object.freeze({
  js: ["javascript"],
  html: ["html", "html5"],
  css: ["css", "css3"],
  ts: ["typescript"],
  py: ["python"],
  java: ["java", "openjdk"],
  tailwind: ["tailwindcss"],
  vue: ["vuejs", "vuedotjs"],
  vuejs: ["vuejs", "vuedotjs"],
  nuxt: ["nuxtjs", "nuxt"],
  nuxtjs: ["nuxtjs", "nuxt"],
  go: ["golang", "go"],
  golang: ["golang", "go"],
  cf: ["cloudflare"],
  azure: ["azure", "microsoftazure"],
  wasm: ["webassembly"],
  postgres: ["postgresql"],
  k8s: ["kubernetes"],
  next: ["nextjs", "nextdotjs"],
  nextjs: ["nextjs", "nextdotjs"],
  mongo: ["mongodb"],
  md: ["markdown"],
  ps: ["photoshop", "adobephotoshop"],
  photoshop: ["photoshop", "adobephotoshop"],
  ai: ["illustrator", "adobeillustrator"],
  illustrator: ["illustrator", "adobeillustrator"],
  pr: ["premiere", "adobepremierepro"],
  premiere: ["premiere", "adobepremierepro"],
  ae: ["aftereffects", "adobeaftereffects"],
  aftereffects: ["aftereffects", "adobeaftereffects"],
  scss: ["sass"],
  sc: ["scala"],
  net: ["dotnet"],
  gatsbyjs: ["gatsby"],
  gql: ["graphql"],
  vlang: ["v"],
  aws: ["aws", "amazonwebservices"],
  amazonwebservices: ["aws", "amazonwebservices"],
  bots: ["discordbots", "discord"],
  express: ["expressjs", "express"],
  expressjs: ["expressjs", "express"],
  googlecloud: ["gcp", "googlecloud"],
  gcp: ["gcp", "googlecloud"],
  mui: ["materialui", "mui"],
  materialui: ["materialui", "mui"],
  windi: ["windicss"],
  unreal: ["unrealengine"],
  nest: ["nestjs"],
  ktorio: ["ktor"],
  pwsh: ["powershell"],
  au: ["audition", "adobeaudition"],
  audition: ["audition", "adobeaudition"],
  rollup: ["rollupjs", "rollupdotjs"],
  rollupjs: ["rollupjs", "rollupdotjs"],
  rxjs: ["reactivex"],
  rxjava: ["reactivex"],
  ghactions: ["githubactions"],
  sklearn: ["scikitlearn"],
  nodejs: ["nodejs", "nodedotjs"],
});
